"""
Confluent Kafka stub
"""

from typing import Any, Dict, Optional

class Producer:
    def __init__(self, config: Dict[str, Any]) -> None: ...
    def produce(
        self, topic: str, value: bytes, key: Optional[bytes] = None
    ) -> None: ...
    def flush(self) -> None: ...
    def poll(self, timeout: float) -> None: ...

class Consumer:
    def __init__(self, config: Dict[str, Any]) -> None: ...
    def subscribe(self, topics: list[str]) -> None: ...
    def poll(self, timeout: float) -> Optional[Any]: ...
    def commit(self) -> None: ...
