"""Confluent Kafka stub."""

from typing import Any

class Producer:
    def __init__(self, config: dict[str, Any]) -> None: ...
    def produce(self, topic: str, value: bytes, key: bytes | None = None) -> None: ...
    def flush(self) -> None: ...
    def poll(self, timeout: float) -> None: ...

class Consumer:
    def __init__(self, config: dict[str, Any]) -> None: ...
    def subscribe(self, topics: list[str]) -> None: ...
    def poll(self, timeout: float) -> Any | None: ...
    def commit(self) -> None: ...
