from typing import Any, List

class FeatureStore:
    def apply(self, objects: List[Any]) -> None: ...
    def get_historical_features(
        self, entity_df: Any, feature_refs: List[str]
    ) -> Any: ...
    def push(self, source: Any, to: str = "online") -> None: ...

class Entity:
    def __init__(self, name: str, **kwargs): ...

class FeatureView:
    def __init__(self, name: str, entities: List[str], **kwargs): ...

class Field:
    def __init__(self, name: str, dtype: Any): ...

class FileSource:
    def __init__(self, path: str, **kwargs): ...

class RepoConfig:
    def __init__(self, **kwargs): ...
