#!/bin/bash
# 调试语法错误的脚本

echo "检查文件: src/adapters/factory_simple.py"
python -m py_compile "src/adapters/factory_simple.py"
echo "---"
echo "检查文件: src/adapters/factory.py"
python -m py_compile "src/adapters/factory.py"
echo "---"
echo "检查文件: src/adapters/registry.py"
python -m py_compile "src/adapters/registry.py"
echo "---"
echo "检查文件: src/adapters/football.py"
python -m py_compile "src/adapters/football.py"
echo "---"
echo "检查文件: src/config/openapi_config.py"
python -m py_compile "src/config/openapi_config.py"
echo "---"
echo "检查文件: src/api/schemas.py"
python -m py_compile "src/api/schemas.py"
echo "---"
echo "检查文件: src/api/cqrs.py"
python -m py_compile "src/api/cqrs.py"
echo "---"
echo "检查文件: src/api/buggy_api.py"
python -m py_compile "src/api/buggy_api.py"
echo "---"
echo "检查文件: src/api/dependencies.py"
python -m py_compile "src/api/dependencies.py"
echo "---"
echo "检查文件: src/api/data_router.py"
python -m py_compile "src/api/data_router.py"
echo "---"
