version: '3.8'

services:
  # Jaeger - 分布式追踪系统
  jaeger:
    image: jaegertracing/all-in-one:1.50
    container_name: football-jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # HTTP collector
      - "14250:14250"  # gRPC collector
      - "6831:6831/udp"  # UDP agent
      - "6832:6832/udp"  # UDP agent
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:14269/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.89.0
    container_name: football-otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./monitoring/tracing/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter
    networks:
      - monitoring
    depends_on:
      jaeger:
        condition: service_healthy
    environment:
      - JAEGER_ENDPOINT=jaeger:14250
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8888/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Zipkin（可选，用于兼容）
  zipkin:
    image: openzipkin/zipkin:2.24
    container_name: football-zipkin
    restart: unless-stopped
    ports:
      - "9411:9411"
    networks:
      - monitoring
    environment:
      - STORAGE_TYPE=mem
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9411/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  jaeger-data:
    driver: local

networks:
  monitoring:
    driver: bridge
    external: true
