version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - PYTHONPATH=/app
    volumes:
      - .:/app
      - /app/venv
      - ./logs:/app/logs
    stdin_open: true
    tty: true
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"  # Redis port for development
    volumes:
      - redis_dev_data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      # 修复：统一使用足球预测系统的数据库配置
      POSTGRES_DB: ${POSTGRES_DB:-football_prediction_dev}
      POSTGRES_USER: ${POSTGRES_USER:-football_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  # 开发工具
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  # Redis管理界面
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  postgres_dev_data:
  redis_dev_data:
