version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: footballprediction-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - mcp-network

volumes:
  grafana_data:

networks:
  mcp-network:
    driver: bridge
