# Docker Compose for Test Environment
# 专门用于测试环境的轻量级服务配置，仅包含CI测试必需的服务

version: '3.8'

services:
  # PostgreSQL数据库 - 测试环境
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: football_prediction_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d football_prediction_test"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    tmpfs:
      - /var/lib/postgresql/data
    restart: unless-stopped

  # Redis缓存服务 - 测试环境
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    tmpfs:
      - /data
    restart: unless-stopped

networks:
  default:
    name: football_test_network
    driver: bridge
