[pytest]
# 设置源代码路径，解决 ModuleNotFoundError
pythonpath = . src
testpaths = tests
# 忽略一些无关的警告
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
# 设置异步模式 (因为我们用了 pytest-asyncio)
asyncio_mode = auto
