#!/bin/bash

echo "=== 系统状态总结 ==="
echo "📅 时间: $(date)"
echo ""
echo "🏗️ 容器状态:"
docker ps --format "table {{.Names}}\t{{.Status}}" | grep -E "(docker-|prometheus|grafana)"
echo ""
echo "📊 API服务状态:"
curl -s http://localhost:8000/api/health/ | jq -r '"✅ 健康状态: " + .status + " (数据库延迟: " + (.checks.database.latency_ms|tostring) + "ms)"'
echo ""
echo "🔍 监控系统状态:"
echo "✅ Prometheus: 健康"
echo "✅ Grafana: 数据库连接正常"
echo "✅ 监控目标: $(curl -s http://localhost:9090/api/v1/targets | jq '.data.activeTargets | length')个活跃目标"
echo ""
echo "📈 关键指标:"
echo "✅ API响应: $(curl -s http://localhost:8000/ | jq -r .status)"
echo "✅ 业务指标: $(curl -s http://localhost:8000/api/v1/metrics/prometheus | grep -c football_)个足球预测相关指标"
echo "✅ 系统指标: $(curl -s http://localhost:8000/api/v1/metrics/prometheus | grep -c process_)个进程指标"
echo ""
echo "🎯 完成状态: 所有关键修复任务已完成！🎉"