apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    isDefault: false
    editable: true
    jsonData:
      poolSize: 5
      timeout: 10
      pingInterval: 30
    secureJsonData:
      password: ""