# Stubs for requests library
from typing import Any, Dict

class Response:
    status_code: int
    text: str
    content: bytes

    def json(self) -> Dict[str, Any]: ...
    def raise_for_status(self) -> None: ...

def get(url: str, **kwargs: Any) -> Response: ...
def post(url: str, **kwargs: Any) -> Response: ...
def put(url: str, **kwargs: Any) -> Response: ...
def delete(url: str, **kwargs: Any) -> Response: ...

class Session:
    def get(self, url: str, **kwargs: Any) -> Response: ...
    def post(self, url: str, **kwargs: Any) -> Response: ...
