FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements-minimal.txt /tmp/requirements-minimal.txt

RUN pip install --upgrade pip \
    && pip install -r /tmp/requirements-minimal.txt \
    && rm -rf /tmp/*

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
