groups:
  - name: api_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{job="football-prediction",status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          service: api
        annotations:
          summary: "API错误率过高"
          description: "API错误率在过去5分钟内为 {{ $value | humanizePercentage }}，超过5%阈值"

      - alert: SlowResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="football-prediction"}[5m])) > 1
        for: 10m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "API响应缓慢"
          description: "API P95响应时间在过去10分钟内为 {{ $value }}s，超过1秒阈值"

      - alert: HighResponseTime
        expr: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{job="football-prediction"}[5m])) > 2
        for: 5m
        labels:
          severity: critical
          service: api
        annotations:
          summary: "API响应非常缓慢"
          description: "API P99响应时间在过去5分钟内为 {{ $value }}s，超过2秒阈值"

      - alert: ServiceDown
        expr: up{job="football-prediction"} == 0
        for: 1m
        labels:
          severity: critical
          service: api
        annotations:
          summary: "API服务不可用"
          description: "API服务 {{ $labels.instance }} 已停止响应"

      - alert: LowRequestRate
        expr: rate(http_requests_total{job="football-prediction"}[5m]) < 10
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "API请求率过低"
          description: "API请求率在过去5分钟内为 {{ $value }} req/s，可能存在异常"

      - alert: MemoryUsageHigh
        expr: (process_resident_memory_bytes / (node_memory_MemTotal_bytes * 1024 * 1024)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "内存使用率过高"
          description: "API服务内存使用率为 {{ $value | printf \"%.2f\" }}%，超过85%"

      - alert: CPUUsageHigh
        expr: 100 * (rate(process_cpu_seconds_total{process_name="football-prediction"}[5m])) > 80
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "CPU使用率过高"
          description: "API服务CPU使用率为 {{ $value | printf \"%.2f\" }}%，超过80%"

      - alert: TooMany4xxErrors
        expr: rate(http_requests_total{job="football-prediction",status=~"4.."}[5m]) / rate(http_requests_total{job="football-prediction"}[5m]) > 0.1
        for: 3m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "4xx错误率过高"
          description: "4xx错误率为 {{ $value | humanizePercentage }}，可能存在客户端配置问题"
