# =================================================================
# 足球预测系统 - Loki 日志聚合配置
# =================================================================

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

# 告警管理器配置
alerting:
  alerts_file_path: /etc/loki/alerts.yml

# ingester 配置
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0

# 模式配置
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# 存储配置
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

# 限制配置
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  per_stream_rate_limit: 1MB
  per_stream_rate_limit_burst: 5MB

# 分片配置
chunk_store_config:
  max_look_back_period: 0s

# 表管理器配置
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

# 查询限制
query_range:
  split_queries_by_interval: 15m
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_items: 1024
        ttl: 5m

# 前端配置
frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  max_outstanding_requests_per_tenant: 4096

# 规则配置
ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  enable_alertmanager_v2: true
  enable_api: true

# 多租户配置
auth_enabled: false

# 分析配置
analytics:
  reporting_enabled: false

# 调试配置
debug:
  addr: 0.0.0.0
  port: 6060
  pprof_enabled: false