# Kubernetes Deployment
# Kubernetes部署配置
# 生成时间: 2025-10-26 20:57:41

apiVersion: apps/v1
kind: Deployment
metadata:
  name: footballprediction-api
  namespace: footballprediction
  labels:
    app: footballprediction-api
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: footballprediction-api
  template:
    metadata:
      labels:
        app: footballprediction-api
        version: v1
    spec:
      containers:
      - name: api
        image: footballprediction/api:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: footballprediction-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: footballprediction-secrets
              key: redis-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config

      volumes:
      - name: config-volume
        configMap:
          name: footballprediction-config

---
apiVersion: v1
kind: Service
metadata:
  name: footballprediction-api-service
  namespace: footballprediction
spec:
  selector:
    app: footballprediction-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: footballprediction-api-hpa
  namespace: footballprediction
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: footballprediction-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
