#!/usr/bin/env python3
"""TeamNameNormalizer 的规则常量。"""

from __future__ import annotations

TEAM_NAME_MAPPINGS = {
    "man utd": "manchester united",
    "man united": "manchester united",
    "manchester utd": "manchester united",
    "man city": "manchester city",
    "mancity": "manchester city",
    "leeds": "leeds united",
    "leicester": "leicester city",
    "newcastle": "newcastle united",
    "newcastle utd": "newcastle united",
    "tottenham": "tottenham hotspur",
    "spurs": "tottenham hotspur",
    "west ham": "west ham united",
    "wolves": "wolverhampton wanderers",
    "nottm forest": "nottingham forest",
    "nottingham": "nottingham forest",
    "atleti": "atletico madrid",
    "atletico": "atletico madrid",
    "real madrid": "real madrid",
    "barca": "barcelona",
    "fc barcelona": "barcelona",
    "real betis": "real betis",
    "real sociedad": "real sociedad",
    "r. sociedad": "real sociedad",
    "r sociedad": "real sociedad",
    "real valladolid": "real valladolid",
    "ath bilbao": "athletic bilbao",
    "athletic bilbao": "athletic bilbao",
    "valencia cf": "valencia",
    "espanyol": "espanyol",
    "bayern munich": "bayern munich",
    "bayern munchen": "bayern munich",
    "b dortmund": "borussia dortmund",
    "bvb": "borussia dortmund",
    "b leverkusen": "bayer leverkusen",
    "bayer leverkusen": "bayer leverkusen",
    "e frankfurt": "eintracht frankfurt",
    "eintracht frankfurt": "eintracht frankfurt",
    "inter milan": "inter milan",
    "inter": "inter milan",
    "ac milan": "milan",
    "juve": "juventus",
    "juventus": "juventus",
    "napoli": "napoli",
    "roma": "roma",
    "as roma": "roma",
    "lazio": "lazio",
    "psg": "paris saint germain",
    "paris sg": "paris saint germain",
    "olympique marseille": "marseille",
    "marseille": "marseille",
    "olympique lyon": "lyon",
    "lyon": "lyon",
    "nice": "nice",
    "monaco": "monaco",
    "benfica": "benfica",
    "sporting cp": "sporting lisbon",
    "sporting lisbon": "sporting lisbon",
    "porto": "porto",
    "fc porto": "porto",
    "ajax": "ajax",
    "afc ajax": "ajax",
    "feyenoord": "feyenoord",
    "psv": "psv eindhoven",
    "psv eindhoven": "psv eindhoven",
}

SUFFIXES_TO_STRIP = [
    r"\s+fc$",
    r"\s+f\.c\.$",
    r"\s+afcd?$",
    r"\s+a\.f\.c\.d?$",
    r"\s+cf$",
    r"\s+c\.f\.$",
    r"\s+sc$",
    r"\s+s\.c\.$",
    r"\s+ac$",
    r"\s+a\.c\.$",
    r"\s+sd$",
    r"\s+s\.d\.$",
    r"\s+town$",
    r"\s+athletic$",
]

PREFIXES_TO_STRIP = [
    r"^afc\s+",
    r"^AFC\s+",
    r"^fc\s+",
    r"^FC\s+",
]
