from typing import Any

class FeatureStore:
    def apply(self, objects: list[Any]) -> None: ...
    def get_historical_features(
        self, entity_df: Any, feature_refs: list[str]
    ) -> Any: ...
    def push(self, source: Any, to: str = "online") -> None: ...

class Entity:
    def __init__(self, name: str, **kwargs): ...

class FeatureView:
    def __init__(self, name: str, entities: list[str], **kwargs): ...

class Field:
    def __init__(self, name: str, dtype: Any): ...

class FileSource:
    def __init__(self, path: str, **kwargs): ...

class RepoConfig:
    def __init__(self, **kwargs): ...
