from typing import Any

class DataContext:
    def get_datasource(self, name: str) -> Any: ...
    def add_expectation_suite(self, suite: Any) -> None: ...

class ExpectationSuite:
    def __init__(self, name: str): ...
