from typing import Any

class Process:
    def cpu_percent(self) -> float: ...
    def memory_info(self) -> Any: ...

def cpu_percent(interval: float = 0.1) -> float: ...
def virtual_memory() -> Any: ...
