'use strict';
const assert = require('node:assert/strict'); const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path'); const { spawnSync } = require('node:child_process'); const test = require('node:test');
const { seedFotMobFixtureUniverse } = require('../../../src/infrastructure/fixture_universe/FixtureUniverse'); const { persistVerifiedAllocationAuthority } = require('../../../src/infrastructure/fixture_universe/AllocationAuthorityArtifact'); const { sha256Text } = require('../../../src/infrastructure/market_evidence/contracts'); const { bootstrapMarketEvidenceTransactionStore } = require('../../../src/infrastructure/market_evidence/transactionStore'); const { openMarketEvidenceAuthoritySnapshot } = require('../../../src/infrastructure/market_evidence/authorityReader'); const { buildProspectiveMarketEvidenceTransaction } = require('../../../src/infrastructure/market_evidence/prospectiveBatch'); const { publishProspectiveMarketEvidenceTransaction } = require('../../../src/infrastructure/market_evidence/atomicPublisher');
function fixtures() { const allMatches=Array.from({length:380},(_,i)=>({id:String(810000+i),home:{name:i?`Home ${i}`:'Arsenal'},away:{name:i?`Away ${i}`:'Chelsea'},status:{utcTime:i?`2026-10-${String((i%28)+1).padStart(2,'0')}T15:00:00Z`:'2026-09-12T15:00:00Z'}})); return `<script id="__NEXT_DATA__" type="application/json">${JSON.stringify({query:{season:'2026/2027'},props:{pageProps:{details:{id:47},fixtures:{allMatches}}}})}</script>`; }
function setup(t) { const root=fs.mkdtempSync(path.join(os.tmpdir(),'atomic-publisher-')); t.after(()=>fs.rmSync(root,{recursive:true,force:true})); let n=0; const raw=fixtures(); const universe=seedFotMobFixtureUniverse({rawHtml:raw,rawSha256:sha256Text(raw),manifest:{raw_file_relative_path:'fixture.html'},allocate:p=>`${p}_${++n}`,mode:'INITIAL_SEED'}); const allocationPath=path.join(root,'allocation.json'); persistVerifiedAllocationAuthority({artifactPath:allocationPath,allocationAuthority:universe.allocationAuthority}); const storeRoot=path.join(root,'store'); bootstrapMarketEvidenceTransactionStore({storeRoot,allocationArtifactPath:allocationPath,bootstrapMetadata:{test:'atomic'}}); return {universe,storeRoot,allocationPath}; }
function candidate(ctx, id = 'e0', unknown = false, captureTag = '') { const home=unknown?'Unknown FC':'Arsenal'; const event={id,sport_key:'soccer_epl',home_team:home,away_team:'Chelsea',commence_time:'2026-09-12T15:00:00Z',bookmakers:[{key:'book',title:'Book',markets:[{key:'h2h',outcomes:[{name:home,price:2},{name:'Draw',price:3},{name:'Chelsea',price:4}]}]}]}; const oddsRawText=JSON.stringify([event]); const captureReceipt={provider:'the-odds-api',capture_id:`capture-${id}-${unknown?'q':'m'}${captureTag}`,raw_sha256:sha256Text(oddsRawText),request_started_at:'2026-08-27T13:31:20Z',response_received_at:'2026-08-27T13:31:49Z',ingested_at:'2026-08-27T13:31:49Z',acquisition_mode:'HISTORICAL_FILE',raw_evidence_reference:'raw/x'}; return buildProspectiveMarketEvidenceTransaction({authoritySnapshot:openMarketEvidenceAuthoritySnapshot({storeRoot:ctx.storeRoot,allocationArtifactPath:ctx.allocationPath}),universe:ctx.universe,oddsRawText,captureReceipt}); }
function publish(ctx, candidateValue, extra = {}) { return publishProspectiveMarketEvidenceTransaction({ storeRoot: ctx.storeRoot, allocationArtifactPath: ctx.allocationPath, candidate: candidateValue, ...extra }); }
test('VALID_CANDIDATE_ATOMIC_PUBLISH_PASS and IDENTICAL_TRANSACTION_IDEMPOTENT',t=>{const ctx=setup(t);const c=candidate(ctx);const one=publish(ctx,c);assert.equal(one.status,'COMMITTED');assert.equal(one.snapshot.head_transaction_id,c.transaction_id);assert.equal(one.snapshot.observations.length,3);const two=publish(ctx,c);assert.equal(two.reused,true);assert.equal(two.snapshot.head_transaction_id,c.transaction_id);});
test('SECOND_STAGING_WRITE_FAILURE_ZERO_AUTHORITY',t=>{const ctx=setup(t);const c=candidate(ctx);const before=openMarketEvidenceAuthoritySnapshot({storeRoot:ctx.storeRoot,allocationArtifactPath:ctx.allocationPath});assert.throws(()=>publish(ctx,c,{fault:'observations.jsonl'}),/injected failure/);const after=openMarketEvidenceAuthoritySnapshot({storeRoot:ctx.storeRoot,allocationArtifactPath:ctx.allocationPath});assert.equal(after.state_hash,before.state_hash);assert.equal(fs.existsSync(path.join(ctx.storeRoot,'committed',c.transaction_id)),false);assert.equal(fs.existsSync(path.join(ctx.storeRoot,'.staging',c.transaction_id)),true);});
test('STALE_PARENT_TRANSACTION_REJECTED and PRE_RENAME_FAILURE_ZERO_AUTHORITY',t=>{const ctx=setup(t);const c=candidate(ctx);assert.throws(()=>publish(ctx,c,{fault:'before-rename'}),/injected failure/);assert.equal(openMarketEvidenceAuthoritySnapshot({storeRoot:ctx.storeRoot,allocationArtifactPath:ctx.allocationPath}).head_transaction_id,null);const fresh=candidate(ctx,'fresh');publish(ctx,fresh);assert.throws(()=>publish(ctx,c),/staging residue|authoritative head/);});
test('all pre-rename write, fsync, staging-reopen and rename failures leave zero authority', t => {
    for (const fault of ['identity_decisions.jsonl', 'manifest.json', 'COMMITTED', 'identity_decisions.jsonl:fsync', 'manifest.json:fsync', 'staging-directory-fsync', 'staging-tamper', 'before-rename', 'rename']) {
        const ctx = setup(t); const c = candidate(ctx); const before = openMarketEvidenceAuthoritySnapshot({ storeRoot: ctx.storeRoot, allocationArtifactPath: ctx.allocationPath });
        assert.throws(() => publish(ctx, c, { fault }));
        const after = openMarketEvidenceAuthoritySnapshot({ storeRoot: ctx.storeRoot, allocationArtifactPath: ctx.allocationPath });
        assert.equal(after.state_hash, before.state_hash, fault); assert.equal(after.head_transaction_id, before.head_transaction_id, fault); assert.equal(fs.existsSync(path.join(ctx.storeRoot, 'committed', c.transaction_id)), false, fault);
    }
});
test('post-rename parent fsync error is authoritatively resolved as full committed transaction', t => { const ctx=setup(t); const c=candidate(ctx); const result=publish(ctx,c,{fault:'committed-directory-fsync'}); assert.equal(result.status,'COMMITTED'); assert.equal(result.snapshot.head_transaction_id,c.transaction_id); assert.equal(result.snapshot.observations.length,3); });
test('MATCHED_QUARANTINED_MATCHED_ACROSS_TRANSACTIONS', t => { const ctx=setup(t); const one=candidate(ctx); publish(ctx,one); let snapshot=openMarketEvidenceAuthoritySnapshot({storeRoot:ctx.storeRoot,allocationArtifactPath:ctx.allocationPath}); const two=candidate(ctx,'e0',true); publish(ctx,two); snapshot=openMarketEvidenceAuthoritySnapshot({storeRoot:ctx.storeRoot,allocationArtifactPath:ctx.allocationPath}); const three=candidate(ctx,'e0',false,'-recover'); publish(ctx,three); snapshot=openMarketEvidenceAuthoritySnapshot({storeRoot:ctx.storeRoot,allocationArtifactPath:ctx.allocationPath}); assert.equal(snapshot.decisions.length,3); assert.equal(two.identity_decisions[0].supersedes_decision_id,one.identity_decisions[0].identity_decision_id); assert.equal(three.identity_decisions[0].supersedes_decision_id,two.identity_decisions[0].identity_decision_id); assert.equal(snapshot.latestDecision('the-odds-api','e0').decision,'MATCHED'); assert.equal(snapshot.activeMatched('the-odds-api','e0').identity_decision_id,three.identity_decisions[0].identity_decision_id); assert.equal(snapshot.head_transaction_id,three.transaction_id); assert.equal(snapshot.state_hash,three.post_state_hash); assert.equal(two.observations.length,0); });
test('CROSS_PROCESS_POST_COMMIT_REOPEN', t => { const ctx=setup(t); const c=candidate(ctx); publish(ctx,c); const program="const r=require('./src/infrastructure/market_evidence/authorityReader');const s=r.openMarketEvidenceAuthoritySnapshot({storeRoot:process.argv[1],allocationArtifactPath:process.argv[2]});process.stdout.write(JSON.stringify({id:s.head_transaction_id,state:s.state_hash,decisions:s.decisions.length,observations:s.observations.length}))"; const child=spawnSync(process.execPath,['-e',program,ctx.storeRoot,ctx.allocationPath],{cwd:path.resolve(__dirname,'../../..'),encoding:'utf8'}); assert.equal(child.status,0,child.stderr); const got=JSON.parse(child.stdout); assert.deepEqual(got,{id:c.transaction_id,state:c.post_state_hash,decisions:1,observations:3}); });
