import type { User, LoginCredentials, RegisterData } from '@/types/auth';
import type { UserProfile } from '@/types/prediction';
export declare const useAuthStore: import("pinia").StoreDefinition<"auth", Pick<{
    user: any;
    token: any;
    loading: any;
    error: any;
    isAuthenticated: import("vue").ComputedRef<boolean>;
    isAdmin: import("vue").ComputedRef<boolean>;
    userName: import("vue").ComputedRef<string>;
    userRole: import("vue").ComputedRef<"user" | "admin">;
    login: (credentials: LoginCredentials) => Promise<boolean>;
    register: (data: RegisterData) => Promise<boolean>;
    logout: () => Promise<void>;
    checkAuth: () => boolean;
    refreshAuth: () => Promise<boolean>;
    updateProfile: (updates: Partial<User>) => Promise<boolean>;
    clearError: () => void;
    clearAuth: () => void;
    setUser: (profileData: UserProfile) => void;
    updateBankroll: (newBankroll: number) => void;
}, any>, Pick<{
    user: any;
    token: any;
    loading: any;
    error: any;
    isAuthenticated: import("vue").ComputedRef<boolean>;
    isAdmin: import("vue").ComputedRef<boolean>;
    userName: import("vue").ComputedRef<string>;
    userRole: import("vue").ComputedRef<"user" | "admin">;
    login: (credentials: LoginCredentials) => Promise<boolean>;
    register: (data: RegisterData) => Promise<boolean>;
    logout: () => Promise<void>;
    checkAuth: () => boolean;
    refreshAuth: () => Promise<boolean>;
    updateProfile: (updates: Partial<User>) => Promise<boolean>;
    clearError: () => void;
    clearAuth: () => void;
    setUser: (profileData: UserProfile) => void;
    updateBankroll: (newBankroll: number) => void;
}, any>, Pick<{
    user: any;
    token: any;
    loading: any;
    error: any;
    isAuthenticated: import("vue").ComputedRef<boolean>;
    isAdmin: import("vue").ComputedRef<boolean>;
    userName: import("vue").ComputedRef<string>;
    userRole: import("vue").ComputedRef<"user" | "admin">;
    login: (credentials: LoginCredentials) => Promise<boolean>;
    register: (data: RegisterData) => Promise<boolean>;
    logout: () => Promise<void>;
    checkAuth: () => boolean;
    refreshAuth: () => Promise<boolean>;
    updateProfile: (updates: Partial<User>) => Promise<boolean>;
    clearError: () => void;
    clearAuth: () => void;
    setUser: (profileData: UserProfile) => void;
    updateBankroll: (newBankroll: number) => void;
}, any>>;
