"""
常量定义模块
集中管理项目中的魔法数字和常量
"""

# HTTP状态码常量
HTTP_STATUS_OK = 200
HTTP_STATUS_CREATED = 201
HTTP_STATUS_BAD_REQUEST = 400
HTTP_STATUS_UNAUTHORIZED = 401
HTTP_STATUS_FORBIDDEN = 403
HTTP_STATUS_NOT_FOUND = 404
HTTP_STATUS_INTERNAL_SERVER_ERROR = 500

# HTTP响应详情常量
DETAIL_INTERNAL_SERVER_ERROR = "内部服务器错误"
DETAIL_UNAUTHORIZED = "未授权访问"
DETAIL_NOT_FOUND = "资源未找到"
DETAIL_BAD_REQUEST = "请求参数错误"

# API响应常量
RESPONSE_SUCCESS = "success"
RESPONSE_ERROR = "error"
RESPONSE_PENDING = "pending"

# 分页常量
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# 缓存常量
CACHE_DEFAULT_TTL = 3600  # 1小时
CACHE_SHORT_TTL = 300    # 5分钟
CACHE_LONG_TTL = 86400   # 24小时

# 业务常量
MAX_RETRY_ATTEMPTS = 3
DEFAULT_TIMEOUT = 30

# 文件路径常量
UPLOAD_DIR = "uploads"
TEMP_DIR = "temp"
LOG_DIR = "logs"