# Grafana Prometheus数据源配置
# Grafana Prometheus Datasource Configuration

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "30s"
      queryTimeout: "60s"
      httpMethod: "POST"
      httpHeaderName1: "X-Custom-Header"
      httpHeaderValue1: "FootballPrediction"
    secureJsonData: {}

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
    secureJsonData: {}

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres://postgres:5432/football_prediction
    database: football_prediction
    user: grafana
    secureJsonData:
      password: ${POSTGRES_GRAFANA_PASSWORD}
    jsonData:
      postgresVersion: 130000
      timescaledb: false
      sslmode: "disable"