#!/usr/bin/env bash
# lifecycle: permanent
# M3-D4D-B1 local-only persistent sandbox operator. It never reads project .env.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
PROJECT="fp_m3_persistent_sandbox"; SERVICE="m3-persistent-postgres"; DATABASE="fp_m3_persistent_sandbox"
COMPOSE_FILE="$ROOT/deploy/sandbox/m3_odds_staging/docker-compose.yml"
SECRET_DIR="${HOME}/.config/footballprediction/m3-persistent-sandbox"; BACKUP_DIR="${HOME}/.local/share/footballprediction/backups/m3-persistent-sandbox"
ENV_FILE="$SECRET_DIR/compose.env"; RUNTIME_ENV_FILE="$SECRET_DIR/runtime.env"; PGPASS_FILE="$SECRET_DIR/pgpass"; LOCK_KEY="731642941"
MIGRATIONS=("V26.8__create_odds_historical_staging_contract.sql" "V26.9__add_odds_historical_observation_fingerprint.sql")
die() { echo "BLOCKED: $*" >&2; exit 1; }
require_tool() { command -v "$1" >/dev/null || die "required command missing: $1"; }
compose() { docker compose --env-file "$ENV_FILE" -p "$PROJECT" -f "$COMPOSE_FILE" "$@"; }
safe_identity() { [[ "$PROJECT" == fp_m3_persistent_sandbox && "$SERVICE" == m3-persistent-postgres && "$DATABASE" == fp_m3_persistent_sandbox ]] || die "fixed sandbox identity mismatch"; }
ensure_secret_files() {
  if [[ -e "$SECRET_DIR" && ! -d "$SECRET_DIR" ]]; then die "secret path is not a directory"; fi
  mkdir -p "$SECRET_DIR" "$BACKUP_DIR"; chmod 700 "$SECRET_DIR" "$BACKUP_DIR"
  if [[ -e "$ENV_FILE" || -e "$RUNTIME_ENV_FILE" || -e "$PGPASS_FILE" ]]; then
    [[ -f "$ENV_FILE" && -f "$RUNTIME_ENV_FILE" && -f "$PGPASS_FILE" ]] || die "incomplete existing secret material; refusing overwrite"
    [[ "$(stat -c '%a' "$SECRET_DIR")" == 700 && "$(stat -c '%a' "$ENV_FILE")" == 600 && "$(stat -c '%a' "$RUNTIME_ENV_FILE")" == 600 && "$(stat -c '%a' "$PGPASS_FILE")" == 600 ]] || die "existing secret permissions are unsafe"; return
  fi
  umask 077; local owner migrator writer reader
  owner="$(openssl rand -hex 32)"; migrator="$(openssl rand -hex 32)"; writer="$(openssl rand -hex 32)"; reader="$(openssl rand -hex 32)"
  printf 'M3_SANDBOX_DATABASE=%s\nM3_SANDBOX_OWNER_USER=%s\nM3_SANDBOX_OWNER_PASSWORD=%s\nM3_SANDBOX_SECRET_DIR=%s\nM3_SANDBOX_BACKUP_DIR=%s\nM3_SANDBOX_RUNTIME_ENV_FILE=%s\n' "$DATABASE" fp_m3_sandbox_owner "$owner" "$SECRET_DIR" "$BACKUP_DIR" "$RUNTIME_ENV_FILE" > "$ENV_FILE"
  printf 'M3_SANDBOX_MIGRATOR_PASSWORD=%s\nM3_SANDBOX_WRITER_PASSWORD=%s\nM3_SANDBOX_READER_PASSWORD=%s\n' "$migrator" "$writer" "$reader" > "$RUNTIME_ENV_FILE"
  printf '%s:%s:%s:%s:%s\n%s:%s:%s:%s:%s\n%s:%s:%s:%s:%s\n%s:%s:%s:%s:%s\n' "$SERVICE" 5432 "$DATABASE" fp_m3_sandbox_owner "$owner" "$SERVICE" 5432 "$DATABASE" fp_m3_sandbox_migrator "$migrator" "$SERVICE" 5432 "$DATABASE" fp_m3_sandbox_writer "$writer" "$SERVICE" 5432 "$DATABASE" fp_m3_sandbox_reader "$reader" > "$PGPASS_FILE"; chmod 600 "$ENV_FILE" "$RUNTIME_ENV_FILE" "$PGPASS_FILE"
}
operator_psql() { compose --profile operator run --rm -T --entrypoint psql m3-persistent-operator -X -v ON_ERROR_STOP=1 "$@"; }
owner_psql() { operator_psql -U fp_m3_sandbox_owner "$@"; }
ensure_running() { compose up -d "$SERVICE" >/dev/null; compose ps --status running "$SERVICE" | grep -q "$SERVICE" || die "sandbox service did not start"; }
bootstrap() { safe_identity; require_tool docker; require_tool openssl; ensure_secret_files; ensure_running; owner_psql -f /sandbox-bootstrap/bootstrap_roles.sql; echo "BOOTSTRAPPED project=$PROJECT service=$SERVICE database=$DATABASE postgres=15 host-port=none"; }
ledger_row() { owner_psql -At -c "SELECT sha256_checksum FROM odds_staging_schema_migrations WHERE version='$1'"; }
plan() { safe_identity; [[ -f "$ENV_FILE" ]] || die "run bootstrap first"; ensure_running; for file in "${MIGRATIONS[@]}"; do local version checksum recorded; version="${file%%__*}"; checksum="$(sha256sum "$ROOT/database/migrations/$file" | awk '{print $1}')"; recorded="$(ledger_row "$version")"; if [[ -z "$recorded" ]]; then echo "$version $file $checksum pending"; elif [[ "$recorded" == "$checksum" ]]; then echo "$version $file $checksum already-applied"; else die "checksum-conflict for $version"; fi; done; }
authorize_apply() { [[ "${ALLOW_M3_PERSISTENT_SANDBOX_MIGRATION:-}" == 1 && "${M3_D4D_B1_SANDBOX_MIGRATION_CONFIRMATION:-}" == I_AUTHORIZE_M3_D4D_B1_SANDBOX_MIGRATION ]] || die "explicit sandbox migration authorization required"; }
apply() { safe_identity; authorize_apply; bootstrap; plan; for file in "${MIGRATIONS[@]}"; do local version checksum; version="${file%%__*}"; [[ -z "$(ledger_row "$version")" ]] || continue; checksum="$(sha256sum "$ROOT/database/migrations/$file" | awk '{print $1}')"; compose --profile operator run --rm -T --entrypoint sh m3-persistent-operator -lc "psql -X -v ON_ERROR_STOP=1 -U fp_m3_sandbox_owner -v version='$version' -v filename='$file' -v checksum='$checksum' <<'SQL'
SELECT pg_try_advisory_lock($LOCK_KEY) AS lock_acquired \\gset
\\if :lock_acquired
BEGIN;
SET ROLE fp_m3_sandbox_migrator;
\\i /migrations/$file
INSERT INTO odds_staging_schema_migrations (version,filename,sha256_checksum,applied_by,execution_duration_ms) VALUES (:'version',:'filename',:'checksum',current_user,0);
COMMIT;
SELECT pg_advisory_unlock($LOCK_KEY);
\\else
\\quit
\\endif
SQL" || die "migration $version failed; transaction rolled back"; done; owner_psql -f /sandbox-bootstrap/finalize_staging_grants.sql; status; }
status() { safe_identity; ensure_running; owner_psql -c "SELECT version,filename,sha256_checksum,applied_by FROM odds_staging_schema_migrations ORDER BY version"; owner_psql -c "SELECT 'odds_historical_import_runs' table_name,count(*) row_count FROM odds_historical_import_runs UNION ALL SELECT 'odds_historical_source_files',count(*) FROM odds_historical_source_files UNION ALL SELECT 'odds_historical_staging_observations',count(*) FROM odds_historical_staging_observations UNION ALL SELECT 'odds_historical_quarantine',count(*) FROM odds_historical_quarantine"; }
verify() { safe_identity; status; owner_psql -At -c "SELECT count(*) FROM odds_historical_staging_observations WHERE business_fingerprint IS NULL" | grep -qx 0 || die "NULL fingerprint inventory is nonzero"; owner_psql -At -c "SELECT has_table_privilege('fp_m3_sandbox_writer','odds_historical_quarantine','insert') AND NOT has_table_privilege('fp_m3_sandbox_writer','odds_historical_quarantine','delete') AND NOT has_table_privilege('fp_m3_sandbox_reader','odds_historical_quarantine','select')" | grep -qx t || die "role matrix verification failed"; echo "VERIFIED empty-business-inventory=true candidate-identity=not_proven matches-fk=absent"; }
backup() { safe_identity; verify; mkdir -p "$BACKUP_DIR"; chmod 700 "$BACKUP_DIR"; local stamp file operator_id; stamp="$(date -u +%Y%m%dT%H%M%SZ)"; file="$BACKUP_DIR/m3-persistent-sandbox-$stamp.dump"; compose --profile operator create m3-persistent-operator >/dev/null; operator_id="$(compose --profile operator ps -aq m3-persistent-operator)"; [[ -n "$operator_id" ]] || die "sandbox backup operator was not created"; docker start "$operator_id" >/dev/null; docker exec "$operator_id" pg_dump -U fp_m3_sandbox_owner -Fc -f /tmp/m3-sandbox-backup.dump; docker cp "$operator_id:/tmp/m3-sandbox-backup.dump" "$file"; docker rm -f "$operator_id" >/dev/null; [[ -s "$file" ]] || die "backup extraction failed"; chmod 600 "$file"; sha256sum "$file" > "$file.sha256"; chmod 600 "$file.sha256"; echo "BACKUP file=$(basename "$file") sha256=$(awk '{print $1}' "$file.sha256")"; }
stop() { [[ -f "$ENV_FILE" ]] || die "sandbox is not initialized"; compose down --remove-orphans; }
restore_verify() {
  safe_identity; require_tool docker; require_tool openssl
  local backup="${M3_SANDBOX_RESTORE_BACKUP:-}" checksum nonce project db name net dir inv positive role_attributes memberships
  [[ -n "$backup" ]] || die "M3_SANDBOX_RESTORE_BACKUP must name the exact repo-external backup to restore"
  [[ "$backup" == "$BACKUP_DIR"/* && "$backup" == *.dump ]] || die "restore backup must be an exact .dump inside the sandbox backup directory"
  checksum="${backup}.sha256"
  [[ -f "$backup" && -f "$checksum" && "$(sha256sum "$backup" | awk '{print $1}')" == "$(awk '{print $1}' "$checksum")" ]] || die "backup checksum mismatch"
  nonce="$(date -u +%s)_$RANDOM"; project="fp_m3_restore_verify_$nonce"; db="fp_m3_restore_verify_$nonce"; name="${project}-m3-restore-postgres-1"; net="${project}_default"; dir="$(mktemp -d /tmp/m3-restore.XXXXXX)"; chmod 700 "$dir"
  cleanup_restore() { docker rm -f "$name" >/dev/null 2>&1 || true; docker network rm "$net" >/dev/null 2>&1 || true; rm -rf "$dir"; }
  trap cleanup_restore EXIT INT TERM
  umask 077; printf 'POSTGRES_DB=%s\nPOSTGRES_USER=fp_m3_sandbox_owner\nPOSTGRES_PASSWORD=%s\n' "$db" "$(openssl rand -hex 32)" > "$dir/env"; chmod 600 "$dir/env"
  docker network create --label com.footballprediction.scope=m3-d4d-b1-restore-verify --label com.footballprediction.production=false "$net" >/dev/null
  docker run -d --name "$name" --network "$net" --tmpfs /var/lib/postgresql/data:rw,noexec,nosuid,size=256m --env-file "$dir/env" --label com.footballprediction.scope=m3-d4d-b1-restore-verify --label com.footballprediction.production=false postgres:15-alpine >/dev/null
  for _ in $(seq 1 30); do docker exec "$name" sh -lc 'PGPASSWORD="$POSTGRES_PASSWORD" pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"' >/dev/null 2>&1 && break; sleep 1; done
  docker exec "$name" sh -lc 'PGPASSWORD="$POSTGRES_PASSWORD" pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"' >/dev/null || die "clone unavailable"
  docker exec -i "$name" sh -lc 'PGPASSWORD="$POSTGRES_PASSWORD" psql -X -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB"' <<'SQL'
\getenv p POSTGRES_PASSWORD
SELECT format('CREATE ROLE fp_m3_sandbox_migrator NOLOGIN NOINHERIT; CREATE ROLE fp_m3_sandbox_writer LOGIN NOINHERIT PASSWORD %L; CREATE ROLE fp_m3_sandbox_reader LOGIN NOINHERIT PASSWORD %L;', :'p', :'p') \gexec
SELECT format('REVOKE ALL PRIVILEGES ON DATABASE %I FROM PUBLIC', current_database()) \gexec
SELECT format('GRANT CONNECT ON DATABASE %I TO fp_m3_sandbox_migrator,fp_m3_sandbox_writer,fp_m3_sandbox_reader', current_database()) \gexec
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
SQL
  docker cp "$backup" "$name:/tmp/backup.dump"; docker exec "$name" sh -lc 'PGPASSWORD="$POSTGRES_PASSWORD" pg_restore -U "$POSTGRES_USER" -d "$POSTGRES_DB" --exit-on-error /tmp/backup.dump' >/dev/null
  docker cp "$ROOT/database/sandbox/m3_odds_staging/finalize_staging_grants.sql" "$name:/tmp/finalize.sql"; docker exec "$name" sh -lc 'PGPASSWORD="$POSTGRES_PASSWORD" psql -X -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" -f /tmp/finalize.sql' >/dev/null
  owner_sql() { docker exec -i "$name" sh -lc 'PGPASSWORD="$POSTGRES_PASSWORD" psql -X -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" "$@"' sh "$@"; }
  role_sql() { local role="$1"; shift; docker exec -i "$name" sh -lc 'role="$1"; shift; PGPASSWORD="$POSTGRES_PASSWORD" psql -X -v ON_ERROR_STOP=1 -U "$role" -d "$POSTGRES_DB" "$@"' sh "$role" "$@"; }
  scalar() { printf '%s\n' "$1" | owner_sql -At; }
  denial() { local role="$1" probe="$2" command="$3" catalog="$4" before after out rc; before="$(scalar "$catalog")"; set +e; out="$(printf '\\set VERBOSITY verbose\n%s\n' "$command" | role_sql "$role" 2>&1)"; rc=$?; set -e; after="$(scalar "$catalog")"; [[ $rc -ne 0 && "$out" == *42501* && "$before" == "$after" ]] || die "denial failed probe=$probe exit=$rc catalog_before=$before catalog_after=$after stderr=${out//$'\n'/ }"; echo "PROBE name=$probe role=$role exit=$rc sqlstate=42501 expected=42501 result=PASS catalog_delta=0 sanitized_stderr=permission_denied"; }
  [[ "$(scalar "SELECT count(*) FROM information_schema.columns WHERE table_schema=current_schema() AND table_name IN ('odds_historical_import_runs','odds_historical_source_files','odds_historical_staging_observations','odds_historical_quarantine')")" -gt 0 ]] || die "column inventory missing"
  [[ "$(scalar "SELECT count(*) FROM pg_constraint WHERE conrelid IN ('odds_historical_import_runs'::regclass,'odds_historical_source_files'::regclass,'odds_historical_staging_observations'::regclass,'odds_historical_quarantine'::regclass)")" -gt 0 ]] || die "constraint inventory missing"
  [[ "$(scalar "SELECT count(*) FROM pg_indexes WHERE schemaname=current_schema() AND tablename IN ('odds_historical_import_runs','odds_historical_source_files','odds_historical_staging_observations','odds_historical_quarantine')")" -ge 9 ]] || die "index inventory missing"
  [[ "$(scalar "SELECT count(*) FROM odds_staging_schema_migrations WHERE (version='V26.8' AND sha256_checksum='$(sha256sum "$ROOT/database/migrations/V26.8__create_odds_historical_staging_contract.sql" | awk '{print $1}')') OR (version='V26.9' AND sha256_checksum='$(sha256sum "$ROOT/database/migrations/V26.9__add_odds_historical_observation_fingerprint.sql" | awk '{print $1}')')")" == 2 ]] || die "migration ledger/checksum verification failed"
  positive="$(role_sql fp_m3_sandbox_writer -At <<'SQL'
BEGIN;
INSERT INTO odds_historical_import_runs (id,run_key,source_type,mode,status,pipeline_version,expected_accepted_count,expected_quarantine_count,metadata) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',repeat('a',64),'historical_odds','controlled_write','planned','restore-role-probe',1,1,'{"probe":true}'::jsonb);
INSERT INTO odds_historical_source_files (id,import_run_id,source_provider,logical_path,content_hash,hash_algorithm,provenance) VALUES ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','probe-provider','probe://non-real/source.json',repeat('b',64),'sha256','{"probe":true}'::jsonb);
INSERT INTO odds_historical_staging_observations (import_run_id,source_file_id,source_row_number,idempotency_key,canonical_match_id,candidate_match_id,canonical_match_fk_status,historical_match_identity,source_provider,bookmaker,market,selection,decimal_odds,snapshot_type,raw_sha256,raw_record_locator,adapter,adapter_version,provenance_status,match_link_evidence,audit_payload,business_fingerprint) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',1,repeat('c',64),NULL,'probe-candidate-not-a-match','unverified_database_fk','{"probe":true}'::jsonb,'probe-provider','probe-bookmaker','probe-market','probe-selection',2.000000,'unknown',repeat('d',64),'probe://non-real/accepted','restore-role-probe','1','probe-only','{}'::jsonb,'{"probe":true}'::jsonb,repeat('e',64));
INSERT INTO odds_historical_quarantine (import_run_id,source_file_id,source_row_number,quarantine_key,idempotency_key,reason_codes,reason_detail,historical_match_identity,source_payload) VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',2,repeat('f',64),repeat('c',64),'["probe_reason"]'::jsonb,'{"probe":true}'::jsonb,'{"probe":true}'::jsonb,'{"synthetic":true}'::jsonb);
SELECT (SELECT count(*) FROM odds_historical_import_runs),(SELECT count(*) FROM odds_historical_source_files),(SELECT count(*) FROM odds_historical_staging_observations),(SELECT count(*) FROM odds_historical_quarantine),(SELECT count(*) FROM odds_historical_staging_observations WHERE canonical_match_id IS NULL),(SELECT count(*) FROM odds_historical_staging_observations WHERE business_fingerprint IS NOT NULL);
SELECT count(*) FROM odds_historical_import_runs; SELECT count(*) FROM odds_historical_source_files; SELECT count(*) FROM odds_historical_staging_observations; SELECT count(*) FROM odds_historical_quarantine;
UPDATE odds_historical_import_runs SET status='completed',completed_at=NOW() WHERE id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
ROLLBACK;
SQL
)"; [[ "$positive" == *"1|1|1|1|1|1"* && "$positive" == *ROLLBACK* ]] || die "writer positive probe failed output=${positive//$'\n'/ }"; echo "PROBE name=writer_positive role=fp_m3_sandbox_writer result=PASS rows_inside_transaction=1,1,1,1 rollback=true"
  denial fp_m3_sandbox_writer create_role 'CREATE ROLE writer_forbidden_role_probe' "SELECT count(*) FROM pg_roles WHERE rolname='writer_forbidden_role_probe'"
  denial fp_m3_sandbox_writer create_database 'CREATE DATABASE writer_forbidden_database_probe' "SELECT count(*) FROM pg_database WHERE datname='writer_forbidden_database_probe'"
  denial fp_m3_sandbox_writer grant_migrator 'GRANT fp_m3_sandbox_migrator TO fp_m3_sandbox_writer' "SELECT count(*) FROM pg_auth_members WHERE member='fp_m3_sandbox_writer'::regrole AND roleid='fp_m3_sandbox_migrator'::regrole"
  denial fp_m3_sandbox_writer delete 'DELETE FROM odds_historical_staging_observations' "SELECT count(*) FROM odds_historical_staging_observations"; denial fp_m3_sandbox_writer truncate 'TRUNCATE odds_historical_staging_observations' "SELECT count(*) FROM odds_historical_staging_observations"; denial fp_m3_sandbox_writer create_table 'CREATE TABLE writer_forbidden_probe(id integer)' "SELECT count(*) FROM pg_class WHERE relname='writer_forbidden_probe'"; denial fp_m3_sandbox_writer alter_table 'ALTER TABLE odds_historical_staging_observations ADD COLUMN writer_forbidden_column integer' "SELECT count(*) FROM information_schema.columns WHERE table_name='odds_historical_staging_observations' AND column_name='writer_forbidden_column'"; denial fp_m3_sandbox_writer drop_table 'DROP TABLE odds_historical_quarantine' "SELECT count(*) FROM pg_class WHERE oid='odds_historical_quarantine'::regclass"; denial fp_m3_sandbox_writer set_role_migrator 'SET ROLE fp_m3_sandbox_migrator' "SELECT count(*) FROM pg_auth_members WHERE member='fp_m3_sandbox_writer'::regrole AND roleid='fp_m3_sandbox_migrator'::regrole"; denial fp_m3_sandbox_writer set_role_owner 'SET ROLE fp_m3_sandbox_owner' "SELECT count(*) FROM pg_auth_members WHERE member='fp_m3_sandbox_writer'::regrole AND roleid='fp_m3_sandbox_owner'::regrole"
  printf '%s\n' 'SELECT count(*) FROM odds_historical_staging_observations; SELECT count(*) FROM odds_historical_import_runs; SELECT count(*) FROM odds_historical_source_files;' | role_sql fp_m3_sandbox_reader >/dev/null; echo "PROBE name=reader_allowed_select role=fp_m3_sandbox_reader result=PASS"
  denial fp_m3_sandbox_reader quarantine_select 'SELECT * FROM odds_historical_quarantine' "SELECT count(*) FROM odds_historical_quarantine"; denial fp_m3_sandbox_reader insert 'INSERT INTO odds_historical_import_runs DEFAULT VALUES' "SELECT count(*) FROM odds_historical_import_runs"; denial fp_m3_sandbox_reader update "UPDATE odds_historical_import_runs SET status='failed'" "SELECT count(*) FROM odds_historical_import_runs"; denial fp_m3_sandbox_reader delete 'DELETE FROM odds_historical_staging_observations' "SELECT count(*) FROM odds_historical_staging_observations"; denial fp_m3_sandbox_reader create_table 'CREATE TABLE reader_forbidden_probe(id integer)' "SELECT count(*) FROM pg_class WHERE relname='reader_forbidden_probe'"; denial fp_m3_sandbox_reader alter_table 'ALTER TABLE odds_historical_staging_observations ADD COLUMN reader_forbidden_column integer' "SELECT count(*) FROM information_schema.columns WHERE table_name='odds_historical_staging_observations' AND column_name='reader_forbidden_column'"; denial fp_m3_sandbox_reader set_role_writer 'SET ROLE fp_m3_sandbox_writer' "SELECT count(*) FROM pg_auth_members WHERE member='fp_m3_sandbox_reader'::regrole AND roleid='fp_m3_sandbox_writer'::regrole"; denial fp_m3_sandbox_reader set_role_migrator 'SET ROLE fp_m3_sandbox_migrator' "SELECT count(*) FROM pg_auth_members WHERE member='fp_m3_sandbox_reader'::regrole AND roleid='fp_m3_sandbox_migrator'::regrole"; denial fp_m3_sandbox_reader set_role_owner 'SET ROLE fp_m3_sandbox_owner' "SELECT count(*) FROM pg_auth_members WHERE member='fp_m3_sandbox_reader'::regrole AND roleid='fp_m3_sandbox_owner'::regrole"
  [[ "$(scalar "SELECT count(*) FROM pg_auth_members WHERE member IN ('fp_m3_sandbox_writer'::regrole,'fp_m3_sandbox_reader'::regrole) AND roleid IN ('fp_m3_sandbox_owner'::regrole,'fp_m3_sandbox_migrator'::regrole,'fp_m3_sandbox_writer'::regrole)")" == 0 ]] || die "dangerous membership found"; [[ "$(scalar "SELECT count(*) FROM pg_roles WHERE rolname IN ('fp_m3_sandbox_writer','fp_m3_sandbox_reader') AND (rolsuper OR rolcreaterole OR rolcreatedb OR rolbypassrls)")" == 0 ]] || die "unsafe writer/reader role attributes"; [[ "$(scalar "SELECT count(*) FROM pg_namespace n CROSS JOIN LATERAL aclexplode(n.nspacl) a WHERE n.nspname='public' AND a.grantee=0 AND a.privilege_type='CREATE'")" == 0 && "$(scalar "SELECT count(*) FROM pg_roles r WHERE r.rolname IN ('fp_m3_sandbox_writer','fp_m3_sandbox_reader') AND has_schema_privilege(r.oid,'public','CREATE')")" == 0 ]] || die "schema CREATE exposure found"; [[ "$(scalar "SELECT count(*) FROM pg_class c CROSS JOIN LATERAL aclexplode(c.relacl) a WHERE c.relname IN ('odds_historical_import_runs','odds_historical_source_files','odds_historical_staging_observations','odds_historical_quarantine') AND a.grantee=0 AND a.privilege_type IN ('SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER')")" == 0 ]] || die "PUBLIC table privilege exposure found"; [[ "$(scalar "SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace CROSS JOIN LATERAL aclexplode(c.relacl) a WHERE n.nspname=current_schema() AND c.relkind='S' AND a.grantee=0 AND a.privilege_type IN ('USAGE','SELECT','UPDATE')")" == 0 ]] || die "PUBLIC sequence privilege exposure found"; [[ "$(scalar "SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname=current_schema() AND c.relkind='S' AND (NOT has_sequence_privilege('fp_m3_sandbox_writer',c.oid,'USAGE') OR has_sequence_privilege('fp_m3_sandbox_writer',c.oid,'SELECT') OR has_sequence_privilege('fp_m3_sandbox_writer',c.oid,'UPDATE') OR has_sequence_privilege('fp_m3_sandbox_reader',c.oid,'USAGE') OR has_sequence_privilege('fp_m3_sandbox_reader',c.oid,'UPDATE'))")" == 0 ]] || die "sequence least-privilege verification failed"; [[ "$(scalar "SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace CROSS JOIN LATERAL aclexplode(p.proacl) a WHERE n.nspname=current_schema() AND a.grantee=0 AND a.privilege_type='EXECUTE'")" == 0 ]] || die "PUBLIC function execute exposure found"; [[ "$(scalar "SELECT count(*) FROM pg_default_acl d JOIN pg_roles r ON r.oid=d.defaclrole CROSS JOIN LATERAL aclexplode(d.defaclacl) a WHERE r.rolname IN ('fp_m3_sandbox_owner','fp_m3_sandbox_migrator') AND a.grantee IN (0,'fp_m3_sandbox_writer'::regrole,'fp_m3_sandbox_reader'::regrole)")" == 0 ]] || die "unsafe default privilege exposure found"
  role_attributes="$(scalar "SELECT string_agg(rolname||':super='||rolsuper||',inherit='||rolinherit||',createrole='||rolcreaterole||',createdb='||rolcreatedb||',login='||rolcanlogin||',replication='||rolreplication||',bypassrls='||rolbypassrls, ';' ORDER BY rolname) FROM pg_roles WHERE rolname IN ('fp_m3_sandbox_owner','fp_m3_sandbox_migrator','fp_m3_sandbox_writer','fp_m3_sandbox_reader')")"; memberships="$(scalar "SELECT coalesce(string_agg(member::regrole::text||'->'||roleid::regrole::text, ';' ORDER BY 1),'none') FROM pg_auth_members WHERE member IN ('fp_m3_sandbox_owner'::regrole,'fp_m3_sandbox_migrator'::regrole,'fp_m3_sandbox_writer'::regrole,'fp_m3_sandbox_reader'::regrole) OR roleid IN ('fp_m3_sandbox_owner'::regrole,'fp_m3_sandbox_migrator'::regrole,'fp_m3_sandbox_writer'::regrole,'fp_m3_sandbox_reader'::regrole)")"; echo "ROLE_AUDIT $role_attributes"; echo "MEMBERSHIP_AUDIT $memberships"; echo "AUDIT roles=passed memberships=passed public_database_create=$(scalar "SELECT count(*) FROM pg_database d CROSS JOIN LATERAL aclexplode(d.datacl) a WHERE d.datname=current_database() AND a.grantee=0 AND a.privilege_type='CREATE'") public_schema_create=false public_table_dml=false public_sequence_privileges=false functions_in_schema=$(scalar "SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname=current_schema()") default_acl_rows=$(scalar "SELECT count(*) FROM pg_default_acl WHERE defaclrole IN ('fp_m3_sandbox_owner'::regrole,'fp_m3_sandbox_migrator'::regrole)")"
  inv="$(scalar "SELECT (SELECT count(*) FROM odds_staging_schema_migrations),(SELECT count(*) FROM odds_historical_import_runs),(SELECT count(*) FROM odds_historical_source_files),(SELECT count(*) FROM odds_historical_staging_observations),(SELECT count(*) FROM odds_historical_quarantine),(SELECT count(*) FROM odds_historical_staging_observations WHERE business_fingerprint IS NULL),(SELECT count(*) FROM pg_roles WHERE rolname='writer_forbidden_role_probe'),(SELECT count(*) FROM pg_database WHERE datname='writer_forbidden_database_probe')")"; [[ "$inv" == '2|0|0|0|0|0|0|0' ]] || die "nonzero clone inventory: $inv"
  echo "RESTORE_VERIFY project=$project service=m3-restore-postgres database=$db postgres=15 storage=tmpfs host_ports=none pg_restore=0 ledger=2 rows=0 backup=$(basename "$backup")"; cleanup_restore; trap - EXIT INT TERM
}
# Production wrapper remains fixed to V26.8/V26.9 and has no custom-directory or pause input.
apply() {
  safe_identity; authorize_apply; bootstrap; plan
  local file version container checksum core
  container="$(compose ps -q "$SERVICE")"; [[ -n "$container" ]] || die "sandbox container unavailable"
  core="$ROOT/scripts/ops/odds_staging/m3_migration_runner_core.sh"
  for file in "${MIGRATIONS[@]}"; do
    version="${file%%__*}"; [[ -z "$(ledger_row "$version")" ]] || continue
    checksum="$(sha256sum "$ROOT/database/migrations/$file" | awk '{print $1}')"
    bash "$core" --container "$container" --database "$DATABASE" --file "$ROOT/database/migrations/$file" --checksum "$checksum" --pause-seconds 0 || die "migration $version failed; transaction rolled back"
  done
  owner_psql -f /sandbox-bootstrap/finalize_staging_grants.sql; status
}
case "${1:-}" in
  bootstrap|plan|status|verify|backup|stop) "$1" ;;
  restore_verify) restore_verify ;;
  migrate) apply ;;
  *) echo "usage: $0 {bootstrap|plan|migrate|status|verify|backup|restore_verify|stop}" >&2; exit 2 ;;
esac
