#!/usr/bin/env python3
"""队名别名引擎常量。"""

from __future__ import annotations

TEAM_ABBREVIATIONS: dict[str, str] = {
    "utd": "united",
    "untd": "united",
    "unt": "united",
    "fc": "",
    "afc": "",
    "city": "city",
    "spurs": "tottenham",
    "thfc": "tottenham",
    "whu": "west ham",
    "wh": "west ham",
    "wba": "west bromwich albion",
    "wb": "west bromwich albion",
    "bha": "brighton",
    "bh": "brighton",
    "scouse": "liverpool",
    "reds": "liverpool",
    "blues": "chelsea",
    "gunners": "arsenal",
    "saints": "southampton",
    "posh": "peterborough",
    "addicks": "charlton",
    "robins": "bristol city",
    "tykes": "barnsley",
    "wolves": "wolverhampton wanderers",
    "bvb": "borussia dortmund",
    "om": "olympique marseille",
    "ol": "olympique lyon",
    "psg": "paris saint germain",
    "as": "",
    "ac": "",
    "inter": "internazionale",
    "fcb": "fc barcelona",
    "rma": "real madrid",
    "fcr": "real madrid",
    "ath": "athletic",
    "ss": "",
    "rome": "roma",
}

MULTI_WORD_TEAMS: dict[str, list[str] | str] = {
    "manchester united": ["man utd", "manchester utd", "man untd", "manchester"],
    "manchester city": ["man city", "mancity", "manchester"],
    "west ham united": ["west ham", "west ham utd", "whu", "wh"],
    "west bromwich albion": ["west brom", "wba", "west bromwich", "wb"],
    "tottenham hotspur": ["tottenham", "spurs", "thfc", "tot"],
    "crystal palace": ["crystal pal", "palace", "cp"],
    "newcastle united": ["newcastle", "newcastle utd", "newc", "nufc"],
    "sheffield united": ["sheffield", "sheffield utd", "sheff utd", "sufc"],
    "nottingham forest": ["nottingham", "nottm forest", "nottm", "nffc"],
    "brighton hove albion": ["brighton", "bha", "brighton hove"],
    "leeds united": ["leeds", "leeds utd", "lufc"],
    "leicester city": ["leicester", "leic city", "lcfc"],
    "aston villa": ["aston villa", "villa", "avfc"],
    "london": "",
}

TEAM_PREFIXES: list[str] = [
    "afc ",
    "a.f.c. ",
    "a.c. ",
    "fc ",
    "f.c. ",
]

COMMON_EPL_TEAMS: set[str] = {
    "manchester city",
    "manchester united",
    "manchester utd",
    "man utd",
    "liverpool",
    "chelsea",
    "arsenal",
    "tottenham hotspur",
    "spurs",
    "newcastle united",
    "newcastle",
    "brighton",
    "brighton hove albion",
    "west ham united",
    "west ham",
    "wolverhampton wanderers",
    "wolves",
    "aston villa",
    "leicester city",
    "leicester",
    "everton",
    "southampton",
    "nottingham forest",
    "nottm forest",
    "west bromwich albion",
    "west brom",
    "crystal palace",
    "bournemouth",
    "fulham",
    "leeds united",
    "burnley",
    "sheffield united",
    "norwich city",
    "watford",
    "brentford",
}

CONFIDENCE_THRESHOLD = {
    "HIGH": 90,
    "MEDIUM": 70,
    "LOW": 0,
    "SAFE_MIN": 85,
}

SAME_CITY_DERBIES: dict[str, list[str]] = {
    "manchester": ["manchester united", "manchester city"],
    "milan": ["inter milan", "ac milan"],
    "madrid": ["real madrid", "atletico madrid", "rayo vallecano"],
    "london": [
        "arsenal",
        "tottenham hotspur",
        "chelsea",
        "west ham united",
        "crystal palace",
        "fulham",
        "brentford",
    ],
    "liverpool": ["liverpool", "everton"],
    "ruhr": ["borussia dortmund", "schalke", "bochum"],
    "turin": ["juventus", "torino"],
    "glasgow": ["rangers", "celtic"],
    "athens": ["olympiakos", "panathinaikos", "aek athens"],
    "istanbul": ["galatasaray", "fenerbahce", "besiktas"],
    "rome": ["as roma", "ss lazio", "roma"],
    "zagreb": ["dinamo zagreb", "nk lokomotiva"],
}

TEAM_SUFFIXES: list[str] = [
    "fc",
    "f.c.",
    "cf",
    "c.f.",
    "united",
    "utd",
    "untd",
    "wanderers",
    "city",
    "town",
    "athletic",
    "athletic club",
    "club",
    "ac",
    "a.c.",
    "rb",
    "red bull",
    "inter",
    "internazionale",
    "internazionale milano",
    "milan",
    "milano",
    "hotspur",
    "spurs",
    "forest",
    "albion",
    "palace",
    "crystal",
    "borough",
    "county",
    "rang",
    "rangers",
    "celtic",
    "dynamo",
    "dinamo",
    "sports",
    "sporting",
]

PLACE_NAME_PRIORITY: dict[str, str] = {
    "manchester": "manchester",
    "newcastle": "newcastle",
    "wolverhampton": "wolverhampton",
    "brighton hove": "brighton",
    "west bromwich": "west bromwich",
    "crystal palace": "crystal palace",
    "nottingham": "nottingham",
    "sheffield": "sheffield",
    "stoke city": "stoke",
    "west ham": "west ham",
    "london": "london",
    "liverpool": "liverpool",
    "leeds": "leeds",
    "leicester": "leicester",
    "everton": "everton",
    "bournemouth": "bournemouth",
    "southampton": "southampton",
    "burnley": "burnley",
    "watford": "watford",
    "brentford": "brentford",
    "norwich": "norwich",
    "fulham": "fulham",
    "aston villa": "aston villa",
    "milan": "milan",
    "turin": "turin",
    "roma": "roma",
    "naples": "naples",
    "napoli": "napoli",
    "torino": "torino",
    "genoa": "genoa",
    "genova": "genova",
    "bergamo": "bergamo",
    "atalanta": "atalanta",
    "verona": "verona",
    "bologna": "bologna",
    "florence": "florence",
    "fiorentina": "fiorentina",
    "padua": "padua",
    "padova": "padova",
    "udine": "udine",
    "udinese": "udinese",
    "cagliari": "cagliari",
    "sassuolo": "sassuolo",
    "lecce": "lecce",
    "empoli": "empoli",
    "monza": "monza",
    "salernitana": "salerno",
    "venice": "venice",
    "venezia": "venezia",
    "liguria": "genoa",
    "madrid": "madrid",
    "barcelona": "barcelona",
    "seville": "seville",
    "sevilla": "sevilla",
    "valencia": "valencia",
    "bilbao": "bilbao",
    "san sebastian": "san sebastian",
    "donostia": "san sebastian",
    "real sociedad": "san sebastian",
    "villarreal": "villarreal",
    "vigo": "vigo",
    "celta vigo": "vigo",
    "getafe": "getafe",
    "alaves": "vitoria",
    "valladolid": "valladolid",
    "elche": "elche",
    "mallorca": "mallorca",
    "las palmas": "las palmas",
    "gran canaria": "las palmas",
    "tenerife": "tenerife",
    "cadiz": "cadiz",
    "almeria": "almeria",
    "osasuna": "pamplona",
    "pamplona": "pamplona",
    "rayo vallecano": "madrid",
    "leganes": "leganes",
    "eibar": "eibar",
    "huesca": "huesca",
    "murcia": "murcia",
    "munich": "munich",
    "munchen": "munich",
    "münchen": "munich",
    "dortmund": "dortmund",
    "gelsenkirchen": "gelsenkirchen",
    "schalke": "gelsenkirchen",
    "leverkusen": "leverkusen",
    "leipzig": "leipzig",
    "wolfsburg": "wolfsburg",
    "freiburg": "freiburg",
    "hoffenheim": "hoffenheim",
    "mainz": "mainz",
    "frankfurt": "frankfurt",
    "eintracht frankfurt": "frankfurt",
    "bremen": "bremen",
    "werder": "bremen",
    "augsburg": "augsburg",
    "stuttgart": "stuttgart",
    "koln": "cologne",
    "cologne": "cologne",
    "monchengladbach": "monchengladbach",
    "mgladbach": "monchengladbach",
    "bochum": "bochum",
    "hertha": "berlin",
    "berlin": "berlin",
    "union berlin": "berlin",
    "darmstadt": "darmstadt",
    "heidenheim": "heidenheim",
    "paris": "paris",
    "saint germain": "paris",
    "psg": "paris",
    "marseille": "marseille",
    "lyon": "lyon",
    "monaco": "monaco",
    "lille": "lille",
    "lens": "lens",
    "nice": "nice",
    "rennes": "rennes",
    "strasbourg": "strasbourg",
    "bordeaux": "bordeaux",
    "nantes": "nantes",
    "toulouse": "toulouse",
    "montpellier": "montpellier",
    "reims": "reims",
    "brest": "brest",
    "metz": "metz",
    "lorient": "lorient",
    "clermont": "clermont",
    "troyes": "troyes",
    "angers": "angers",
    "auxerre": "auxerre",
    "le havre": "le havre",
}
