'use strict'; const assert = require('node:assert/strict'); const test = require('node:test'); const fs = require('node:fs'); const path = require('node:path');
const MANIFEST = path.resolve(__dirname, '../../docs/_manifests/fotmob_ligue1_adg52_league_schedule_ssr_probe.json');

test('ADG52 probe found 32/32 targets matched', () => { const a = JSON.parse(fs.readFileSync(MANIFEST, 'utf8')); assert.equal(a.candidate_target_matches_detected_count, 32); assert.equal(a.target_match_ids_matched_count, 32); });
test('ADG52 probe page accessible, __NEXT_DATA__ found', () => { const a = JSON.parse(fs.readFileSync(MANIFEST, 'utf8')); assert.equal(a.successful_http_200_count, 1); assert.equal(a.next_data_marker_found_count, 1); });
test('ADG52 extracted 306 fixtures with route_hash_pairs', () => { const a = JSON.parse(fs.readFileSync(MANIFEST, 'utf8')); assert.ok(a.fixture_count_detected >= 300); assert.ok(a.route_hash_pair_candidates_count >= 300); assert.ok(a.canonical_detail_url_candidates_count >= 300); });
test('ADG52 league schedule data has correct home/away orientation for known pairs', () => { const a = JSON.parse(fs.readFileSync(MANIFEST, 'utf8')); const m = a.result.matched_targets_summary; const t1 = m.find(x => x.target_match_id === '4830473'); assert.ok(t1); assert.equal(t1.candidate_home, 'Paris Saint-Germain'); assert.equal(t1.candidate_away, 'Angers'); });
test('ADG52 no full payload saved', () => { const a = JSON.parse(fs.readFileSync(MANIFEST, 'utf8')); assert.equal(a.full_html_saved, false); assert.equal(a.full_next_data_saved, false); assert.equal(a.full_pageprops_saved, false); assert.equal(a.full_payload_saved, false); });
test('ADG52 safety and write boundaries', () => { const a = JSON.parse(fs.readFileSync(MANIFEST, 'utf8')); const s = a.safety; assert.equal(s.db_write_performed, false); assert.equal(s.raw_write_execution_performed, false); assert.equal(s.full_payload_saved, false); assert.equal(a.raw_write_ready_count, 0); });
