jobs:
  test-matrix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-pip-${{ hashFiles("**/requirements*.lock") }}
        path: ~/.cache/pip
        restore-keys: ${{ runner.os }}-pip-
    - name: Install dependencies
      run: pip install -r requirements/requirements.lock
    - name: Run Phase 7 Test Coverage
      run: python3 scripts/phase7_test_coverage_expander.py
    - name: Run Database Tests
      run: python3 scripts/phase7_database_test_expander.py
    - name: Run Business Logic Tests
      run: python3 scripts/phase7_business_logic_test_expander.py
    - name: Run tests with coverage
      run: pytest tests/${{ matrix.test-type }}/ --cov=src --cov-report=xml --cov-report=html
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
    strategy:
      matrix:
        python-version:
        - '3.11'
        - '3.12'
        test-type:
        - unit
        - integration
        - e2e
name: Enhanced Testing Pipeline
'on':
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    - develop
  schedule:
  - cron: 0 2 * * *
