name: Issue Tracker

on:
  # CI Pipeline 完成时触发
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: [ main, develop ]
  # MLOps 检测到问题时触发
  workflow_run:
    workflows: ["MLOps"]
    types: [completed]
  # 手动创建Issue
  workflow_dispatch:
    inputs:
      issue_type:
        description: 'Type of issue to create'
        required: true
        default: 'bug'
        type: choice
        options:
        - bug
        - enhancement
        - task
        - question
      title:
        description: 'Issue title'
        required: true
        type: string
      description:
        description: 'Issue description'
        required: false
        type: string
      assignee:
        description: 'Assignee username (optional)'
        required: false
        type: string

jobs:
  # 跟踪CI失败
  track-ci-failures:
    name: Track CI Failures
    runs-on: ubuntu-latest
    if: github.event.workflow_run.name == 'CI Pipeline' && github.event.workflow_run.conclusion == 'failure'

    permissions:
      issues: write
      pull-requests: write
      checks: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get CI run details
        id: ci-details
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 获取CI失败的详细信息
          RUN_ID=${{ github.event.workflow_run.id }}
          REPO=${{ github.repository }}

          # 获取失败的job信息
          gh api repos/$REPO/actions/runs/$RUN_ID/jobs > jobs.json

          # 分析失败原因
          FAILED_JOB=$(jq -r '.jobs[] | select(.conclusion == "failure") | .name' jobs.json | head -1)
          FAILED_STEP=$(jq -r '.jobs[] | select(.conclusion == "failure") | .steps[] | select(.conclusion == "failure") | .name' jobs.json | head -1)

          echo "failed-job=$FAILED_JOB" >> $GITHUB_OUTPUT
          echo "failed-step=$FAILED_STEP" >> $GITHUB_OUTPUT
          echo "run-url=https://github.com/$REPO/actions/runs/$RUN_ID" >> $GITHUB_OUTPUT
          echo "commit-sha=$(jq -r '.head_sha' jobs.json)" >> $GITHUB_OUTPUT

      - name: Check for existing issue
        id: check-issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 检查是否已存在相同问题的Issue
          COMMIT=${{ steps.ci-details.outputs.commit-sha }}
          STEP="${{ steps.ci-details.outputs.failed-step }}"

          # 搜索相关的开放Issue
          SEARCH_QUERY="repo:${{ github.repository }} is:open is:issue \"$STEP\""
          EXISTING_ISSUE=$(gh issue list --search "$SEARCH_QUERY" --json number --jq '.[0].number // ""')

          echo "existing-issue=$EXISTING_ISSUE" >> $GITHUB_OUTPUT

      - name: Create or update issue
        if: steps.check-issue.outputs.existing-issue == ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 创建新的Issue
          FAILED_JOB="${{ steps.ci-details.outputs.failed-job }}"
          FAILED_STEP="${{ steps.ci-details.outputs.failed-step }}"
          RUN_URL="${{ steps.ci-details.outputs.run-url }}"
          COMMIT="${{ steps.ci-details.outputs.commit-sha }}"

          ISSUE_TITLE="🐛 CI Failure: $FAILED_STEP"

          ISSUE_BODY=$(cat <<EOF
          ## CI Pipeline Failure

          **Failed Job**: $FAILED_JOB
          **Failed Step**: $FAILED_STEP
          **Commit**: $COMMIT
          **Run**: [View Details]($RUN_URL)

          ### Auto-Generated Details
          This issue was automatically created when the CI pipeline failed.

          ### Next Steps
          1. Investigate the failure in the CI run
          2. Fix the issue in a new branch
          3. The issue will be automatically tracked and updated

          ### Labels
          - type: bug
          - priority: high
          - ci/failed
          - auto-generated

          ---
          *This issue will be automatically closed when the CI pipeline succeeds for the same type of failure.*
          EOF
          )

          # 创建Issue并添加标签
          ISSUE_URL=$(gh issue create \
            --title "$ISSUE_TITLE" \
            --body "$ISSUE_BODY" \
            --label "bug,high priority,ci/failed,auto-generated" \
            --assignee "${{ github.actor }}" \
            --json url \
            --jq .url)

          echo "Created issue: $ISSUE_URL"
          echo "issue-url=$ISSUE_URL" >> $GITHUB_OUTPUT

      - name: Comment on existing issue
        if: steps.check-issue.outputs.existing-issue != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 在现有Issue上添加评论
          ISSUE_NUMBER="${{ steps.check-issue.outputs.existing-issue }}"
          RUN_URL="${{ steps.ci-details.outputs.run-url }}"
          COMMIT="${{ steps.ci-details.outputs.commit-sha }}"

          COMMENT="🔄 CI failed again for commit $COMMIT. [View Details]($RUN_URL)"

          gh issue comment $ISSUE_NUMBER --body "$COMMENT"

      - name: Track issue resolution
        if: steps.check-issue.outputs.existing-issue != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 更新Issue状态，标记为需要关注
          ISSUE_NUMBER="${{ steps.check-issue.outputs.existing-issue }}"

          # 添加"needs-attention"标签
          gh issue edit $ISSUE_NUMBER --add-label "needs-attention"

  # 跟踪MLOps问题
  track-mlops-issues:
    name: Track MLOps Issues
    runs-on: ubuntu-latest
    if: github.event.workflow_run.name == 'MLOps' && github.event.workflow_run.conclusion == 'failure'

    permissions:
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Analyze MLOps failure
        id: mlops-analysis
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RUN_ID=${{ github.event.workflow_run.id }}
          REPO=${{ github.repository }}

          # 获取MLOps运行日志
          gh api repos/$REPO/actions/runs/$RUN_ID/logs > logs.txt

          # 分析失败类型
          if grep -q "Model performance below threshold" logs.txt; then
            echo "failure-type=model-performance" >> $GITHUB_OUTPUT
            echo "issue-title=📉 Model Performance Degradation" >> $GITHUB_OUTPUT
          elif grep -q "Data quality check failed" logs.txt; then
            echo "failure-type=data-quality" >> $GITHUB_OUTPUT
            echo "issue-title=🔍 Data Quality Issues Detected" >> $GITHUB_OUTPUT
          elif grep -q "Retrain check failed" logs.txt; then
            echo "failure-type=retrain-needed" >> $GITHUB_OUTPUT
            echo "issue-title=🔄 Model Retraining Required" >> $GITHUB_OUTPUT
          else
            echo "failure-type=unknown" >> $GITHUB_OUTPUT
            echo "issue-title=⚠️ MLOps Pipeline Failure" >> $GITHUB_OUTPUT
          fi

          echo "run-url=https://github.com/$REPO/actions/runs/$RUN_ID" >> $GITHUB_OUTPUT

      - name: Create MLOps issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TITLE="${{ steps.mlops-analysis.outputs.issue-title }}"
          FAILURE_TYPE="${{ steps.mlops-analysis.outputs.failure-type }}"
          RUN_URL="${{ steps.mlops-analysis.outputs.run-url }}"

          BODY=$(cat <<EOF
          ## MLOps Pipeline Alert

          **Failure Type**: $FAILURE_TYPE
          **Detection Time**: $(date -u +%Y-%m-%d\ %H:%M:%S\ UTC)
          **Run**: [View Details]($RUN_URL)

          ### Recommended Actions

          EOF
          )

          # 根据失败类型添加具体建议
          case $FAILURE_TYPE in
            "model-performance")
              BODY+="
          1. Check recent prediction accuracy
          2. Analyze feature drift
          3. Consider retraining the model
          4. Review recent data quality
              "
              ;;
            "data-quality")
              BODY+="
          1. Review data ingestion pipeline
          2. Check data source integrity
          3. Validate data schema
              "
              ;;
            "retrain-needed")
              BODY+="
          1. Run manual retrain: \`make retrain-check\`
          2. Validate new model performance
          3. Deploy updated model
              "
              ;;
          esac

          BODY+='

          ### Labels
          - type: mlops
          - priority: medium
          - auto-generated

          ---
          *This issue requires attention from the MLOps team.*
          '

          # 创建Issue
          gh issue create \
            --title "$TITLE" \
            --body "$BODY" \
            --label "mlops,$FAILURE_TYPE,auto-generated" \
            --assignee "${{ github.actor }}"

  # 手动创建Issue
  manual-issue:
    name: Create Manual Issue
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    permissions:
      issues: write

    steps:
      - name: Create issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TITLE="${{ github.event.inputs.title }}"
          DESCRIPTION="${{ github.event.inputs.description }}"
          ISSUE_TYPE="${{ github.event.inputs.issue_type }}"
          ASSIGNEE="${{ github.event.inputs.assignee }}"

          # 设置标签
          case $ISSUE_TYPE in
            "bug")
              LABELS="bug,needs-triage"
              ;;
            "enhancement")
              LABELS="enhancement,feature-request"
              ;;
            "task")
              LABELS="task"
              ;;
            "question")
              LABELS="question"
              ;;
          esac

          # 构建Issue内容
          BODY="## Description
          $DESCRIPTION

          ---
          *Created manually via workflow dispatch by @${{ github.actor }}*"

          # 创建Issue
          if [ -n "$ASSIGNEE" ]; then
            gh issue create \
              --title "$TITLE" \
              --body "$BODY" \
              --label "$LABELS" \
              --assignee "$ASSIGNEE"
          else
            gh issue create \
              --title "$TITLE" \
              --body "$BODY" \
              --label "$LABELS"
          fi

  # 自动关闭已解决的Issue
  auto-close-resolved:
    name: Auto-close Resolved Issues
    runs-on: ubuntu-latest
    if: github.event.workflow_run.name == 'CI Pipeline' && github.event.workflow_run.conclusion == 'success'

    permissions:
      issues: write

    steps:
      - name: Check for related issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 获取最近的成功运行
          COMMIT="${{ github.event.workflow_run.head_sha }}"

          # 查找相关的开放Issue
          ISSUES=$(gh issue list \
            --repo "${{ github.repository }}" \
            --label "ci/failed" \
            --state open \
            --json number,title \
            --jq '.[]')

          # 检查是否可以关闭Issue
          echo "$ISSUES" | while read -r issue; do
            ISSUE_NUMBER=$(echo "$issue" | jq -r '.number')
            ISSUE_TITLE=$(echo "$issue" | jq -r '.title')

            # 如果最近的CI成功，关闭相关的失败Issue
            if echo "$ISSUE_TITLE" | grep -q "CI Failure"; then
              echo "Closing issue #$ISSUE_NUMBER: $ISSUE_TITLE"
              gh issue comment $ISSUE_NUMBER \
                --body "✅ This issue has been automatically closed as the CI pipeline is now passing."
              gh issue close $ISSUE_NUMBER
            fi
          done