name: 类型检查 - 简化版本

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]

jobs:
  type-check:
    name: 类型检查
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.lock
          pip install mypy

      - name: Run MyPy type checking
        run: |
          mypy src/ --show-error-codes --json-report mypy-report.json || true

      - name: Generate type checking report
        run: |
          # 简单的类型检查摘要
          echo "## Type Checking Summary" > type-summary.md
          echo "" >> type-summary.md
          echo "Generated at: $(date)" >> type-summary.md
          echo "Commit: $GITHUB_SHA" >> type-summary.md

          if [ -f mypy-report.json ]; then
            echo "MyPy report generated" >> type-summary.md
          else
            echo "MyPy report not available" >> type-summary.md
          fi

      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: type-check-reports
          path: |
            mypy-report.json
            type-summary.md